name: IO
version: 5.0
date: 11/07/2013
description: Bindings for low level C library IO

authors:
    - name: Max Neunhoeffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef/

maintainers:
    - name: Max Neunhoeffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef/

GAP: ">=4.5.5"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.2"

www: http://www-groups.mcs.st-and.ac.uk/~neunhoef/Computer/Software/Gap/io.html
readme: http://www-groups.mcs.st-and.ac.uk/~neunhoef/Computer/Software/Gap/io/README.io
packageinfo: http://www-groups.mcs.st-and.ac.uk/~neunhoef/Computer/Software/Gap/io/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef/Computer/Software/Gap/io/io-5.0.tar.gz

abstract: The <span class="pkgname">IO</span> package, as its name suggests,    provides bindings for <span class="pkgname">GAP</span> to the lower    levels of Input/Output functionality in the C library.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
